### ISSUE TITLE
uri format doesn't include protocol

### ISSUE THREAD

**Issue by shay-thompson** [adobe/ride#27]
### Expected Behaviour
If a schema has format=uri the result value should contain a protocol, such as http://, otherwise its not a valid uri.

### Actual Behaviour
The result is a url without protocol, such as "google.com" instead of "http://google.com"

#### Steps to Reproduce
Give it a schema such as this: https://ns.adobe.com/xdm/context/webpagedetails

**Comment by shay-thompson** [comment]
URI Standard - https://en.m.wikipedia.org/wiki/Uniform_Resource_Identifier

**Comment by shay-thompson** [comment]
Also note - https://tools.ietf.org/html/rfc3986#section-1.1.1

**Comment by tedcasey** [comment]
Fixed with Ride 1.0.6.
