### ISSUE TITLE
model-util: ipv4 generation is invalid

### ISSUE THREAD

**Issue by shay-thompson** [adobe/ride#29]
### Expected Behaviour
Valid ipv4 address

### Actual Behaviour
Occasionally you get an invalid ipv4 address like these:
2.251.0.043
6.053.8.74
3.150.03.014

#### Steps to Reproduce
Generate a bunch of ipv4 address with DataGenerator.generateIPv4()
You can validate them with https://www.regextester.com/95309

**Comment by tedcasey** [comment]
Fixed with Ride 1.0.6.
