### ISSUE TITLE
Support date-time format in model-util

### ISSUE THREAD

**Issue by tedepstein** [adobe/ride#32]
### Expected Behaviour

(Placeholder) When generating a string with `format` equal to `date-time`, model-util should recognize the format and generate a realistic date-time value.

**Comment by tedcasey** [comment]
Sorry, Ted, I remember we discussed this, but can you put some more details in this issue?

Does this not address what you're after?:
https://github.com/adobe/ride/blob/develop/utilities/ride-model-util/src/main/java/com/adobe/ride/utilities/model/ModelObject.java#L431

Is the value generated not realistic enough?

Thanks!

Ted

**Comment by tedepstein** [comment]
Hi @tedcasey, sorry, I don't remember specifics, and I don't know if this has been addressed since I first logged the issue. But it appeared at the time that, given a schema with `type: string` and `format: date-time`, Ride's model-util either did not generate any kind of date-time-like value, or generated a date-time-like value that didn't conform to the `date-time` production as defined in [RFC 3339](https://tools.ietf.org/html/rfc3339), which JSON Schema uses as the [specification for the date-time format](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.1).

If you're familiar with ISO 8601 dates, which are used in XML Schema, I think that's a pretty good reference point for this. RFC 3339 says it's a "profile" (i.e. a subset) of ISO 8601. 

I am not set up to easily run experiments with model-util. Maybe you can try generating some example values with `type: string` and `format: date-time`. If you post the generated example values here, we can discuss how they do or do not conform to the standard.  Again, apologies for not doing this myself when I first posted the issue.

**Comment by tedcasey** [comment]
@tedepstein , [edit] Thanks for the additional info!  Ok, I'll re-review the spec, re-gen some some examples and post for discussion.  Hopefully not too much is required here.

Ted
