### ISSUE TITLE
model-util: generateNodeValue throws NullPointerException

### ISSUE THREAD

**Issue by kachayev** [adobe/ride#33]
[Call](https://github.com/adobe/ride/blob/1eeb58b35d0d87dc509a23d0e6c25ae0fe2d814f/utilities/ride-model-util/src/main/java/com/adobe/ride/utilities/model/ModelObject.java#L548-L552) to `buildNewModelInstance` sets `objectMetadata` to NULL if `presetNodes` is NULL which leads to `NullPointerException` [here](https://github.com/adobe/ride/blob/1eeb58b35d0d87dc509a23d0e6c25ae0fe2d814f/utilities/ride-model-util/src/main/java/com/adobe/ride/utilities/model/ModelObject.java#L1150).

Should `if` statement work other way around?

**Comment by tedcasey** [comment]
Fix in progress.

**Comment by tedcasey** [comment]
Good catch!  Thanks!

**Comment by tedcasey** [comment]
Fixed

**Comment by kachayev** [comment]
Thanks a lot!

**Comment by tedcasey** [comment]
My pleasure, enjoy!  Also, if you notice any other bugs and submit a successful PR, I'll send you a Ride t-shirt.

Thanks again for using Ride!
