### ISSUE TITLE
model-util: presets override any generated data

### ISSUE THREAD

**Issue by shay-thompson** [adobe/ride#34]
### Expected Behaviour
When you supply presets, those values should replace any generated data, only for the fields specified.

### Actual Behaviour
When you supply presets, those presets should only override generated fields of the same name, but instead they're completely overriding the generated fields and sub-fields.  

#### Steps to Reproduce
Using a schema with multiple sub-fields, create a preset that only sets the value for 1 of those sub-fields.  Create a new ModelObject with that preset.  

Lets say your presets json is like this:
`{
  "person" : {
    "name" : {
      "firstName" : "user1"
    }
  }
}`
And your generated json would normally be like this:
`{
  "person" : {
    "name" : {
      "firstName" : "DGGoe61",
      "lastName" : "7U6q0EeKCtsnt",
      "courtesyTitle" : "5gGV5ml7v",
      "fullName" : "dY7GP",
      "middleName" : "Y2Kd10Wtswn5"
    },
    "birthDayAndMonth" : "04-67",
    "birthDate" : "2003-11-25"
  }
}`
What you should have when you create your ModelObject is this:
`{
  "person" : {
    "name" : {
      "firstName" : "user1",
      "lastName" : "7U6q0EeKCtsnt",
      "courtesyTitle" : "5gGV5ml7v",
      "fullName" : "dY7GP",
      "middleName" : "Y2Kd10Wtswn5"
    },
    "birthDayAndMonth" : "04-67",
    "birthDate" : "2003-11-25"
  }
}`
But instead you get this:
`{
  "person" : {
    "name" : {
      "firstName" : "user1"
    }
  }
}`

**Comment by tedcasey** [comment]
Fix implemented.  PR coming soon.

**Comment by tedcasey** [comment]
Fixed
