### ISSUE TITLE
debugging cruft left in code

### ISSUE THREAD

**Issue by enortonAtAdobe** [adobe/ride#49]
https://github.com/adobe/ride/blob/develop/utilities/ride-model-util/src/main/java/com/adobe/ride/utilities/model/ModelObject.java#L742-L744

**Comment by distributedlock** [comment]
I'll take this one.

**Comment by tedcasey** [comment]
Hi Ranadeep.  It looks like Tatiana submitted a PR for this already.  However, I'll try and make time to break up some of the other issues into small ones that are more manageable.  I'll try and post them soon, and if you're still interested, you can tackle one or more of those.

Thanks!

**Comment by distributedlock** [comment]
Hey @tedcasey, that's okay. Sure, I would appreciate that. Please feel free to assign them at your wish to me. I have some time this weekend to contribute. :smile:
