### ISSUE TITLE
Fuzzing of low level (child) objects is not available

### ISSUE THREAD

**Issue by ayush9999-qa** [adobe/ride#59]
### Preconditions:
Request body should contain child objects for eg:
```
{
    test1: {
        "name1":"value1",
        "name2":"value2"
    },
    test2: {
        "name3":"value1",
        "name4":"value2"
    }
}
```

### Expected Behaviour
Fuzz values of all the available parameters ('test1', 'name1', 'name2', 'test2', 'name3', 'name4') should be created

### Actual Behaviour
Fuzz values of only top level objects are created i.e. only for 'test1' and 'test2' in this case

#### Steps to Reproduce
Use request like one stated above for testing and verify the results

**Comment by tedcasey** [comment]
This issue has been resolved with the 2.0.0 release of Ride.  If you disagree, please feel free to re-open the issue.
